## Basic Configuration
baseurl = "https://mentalbreaks.rbind.io/"
languageCode = "en"

theme = "hyde-hyde"

toc = false

## Hugo Built-in Features
disqusShortname = "mentalbreaks"
googleAnalytics = "UA-146526607-1"
# enableRobotsTXT = true

#ignore certain files as recommended
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
    category = "categories"
    tags = "tags"

## Site Settings
[params]
    #themeColor = "theme-base-0d"
    author = "Anthony Nguyen"
    title = "mentalBreaks"
    #description = "Your site's description"
    authorimage = "/img/luckyball_hex.png"
    dateformat = "2 Jan 2006"
    highlightjs = true
    highlightjsTheme = "github-gist"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    instagram = "anguyen1210"
    twitter = "anguyen1210"
    #linkedin = "anguyen1210"
    github = "anguyen1210"
    email = "anguyen1210@gmail.com"

## Main Menu
[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Posts"
    weight = 300
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Projects"
    identifier = "portfolio"
    weight = 400
    url = "/portfolio/"
